(function baseHtmlWrapper(window, module) {
  var parts;
  if (window) {
    parts = window.parts;
  } else {
    parts = require('./parts');
  }
  parts.add('baseHtml', function baseHtml(args) {
    args = args || {};
    args.tabTitle = args.tabTitle || 'Parts';
    args.scripts = args.scripts ||
      '    <script type="text/javascript" src="/parts.js"></script>\n' +
      '    <script src="/horizon/horizon.js"></script>',
    args.directoryPath = args.directoryPath || 'index.html';

    return [
      '<!doctype HTML>',
      '<!-- Generated by parts.baseHtml ' + new Date() + '-->',
      '<html>',
      '  <head>',
      '    <title>' + args.tabTitle + '</title>',
      '    <meta charset="UTF-8">',
      args.scripts,
      '  </head>',
      '  <body>',
      '  </body>',
      '</html>'
    ].join('\n');

  });
})(typeof window === 'undefined' ? null : window,
   typeof module === 'undefined' ? null : module);
